version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:12345@db:5432/mydb?schema=public
    depends_on:
      - db
    volumes:
      - ./microImages:MicroLearning
    networks:
      - app_network
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=mydb
    networks:
      - app_network
    volumes:
      - ./microlearning-postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
   app_network:
    name: network-np